GET http://localhost:3001/api/blogs

################################################################

PUT http://localhost:3001/api/blogs/2
Content-Type: application/json

{
  "likes": 10
}

################################################################
GET http://localhost:3001/api/users

################################################################
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "admin",
  "name": "admin",
  "password": "password"
}

##############################################################
PUT http://localhost:3001/api/users/admin
Content-Type: application/json

{
  "username": "superadmin"
}

##############################################################
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}